### ISSUE TITLE
No such module ReactiveCocoa

### ISSUE THREAD

**Issue by KiritVaghela** [akisute/ReactiveCocoaSwift#1]
Hello 

I download the project and run 'pod install'  and open .xcodewrokspace but now I'm getting error at import ReactiveCocoa.

Do I need to add ReactiveCocoa in Pod?

**Comment by akisute** [comment]
Sorry for bad documentation, but you need to build ReactiveCocoa 3.0 with Carthage, not by CocoaPods. I'll make this more clear(or stop using Carthage completely) later on.

**Comment by akisute** [comment]
OK I tried to replace carthage entirely to cocoapods, but unfortunately the current latest version of ReactiveCocoa in cocoapods (3.0alpha1) doesn't support Swift 1.2 yet. I've set up a branch named `swift1.2` for later on and updated the README documentation to clarify this.

Thank you for your report! :D
